### ISSUE TITLE
Часть "Что такое тестирование интерфейса? (UI testing)" нуждается в экспертных правках.

### ISSUE THREAD

**Issue by ghost** [Vladislav610/QA_bible#2]
Добрый день. Мне кажется, что часть стоит пока вынести в драфты и дать переписать кому-то, кто разбирается в вопросе, так как она вносит больше путаницы, чем разъяснений. Я прочитал первоисточники, с которых был сделан перевод, и там тот же компот.

Причины:

1. Часть называется `"Что такое тестирование интерфейса? (UI testing)"`, но UI - это User Interface, то есть точка взаимодействия пользователя и программы, а в самой части говорится скорее об интерфейсе, как о точке взаимодействия между компонентами системы, а не между пользователем и системой. Иными словами, каждый UI - это интерфейс, но не каждый интерфейс - это UI.

2. `"Это тип интеграционного теста, который проверяет, правильно ли установлена связь между двумя различными программными системами. "` Это могут быть не системы, а части системы, то есть модули программы.

3. `"На самом деле интерфейс — это программное обеспечение, состоящее из наборов команд, сообщений и других атрибутов, которые обеспечивают связь **между устройством и пользователем**."`, но чуть выше говорится "`Соединение, которое объединяет два компонента, называется интерфейсом`" и `"связь между двумя различными программными системами"`

4. `"Тестирование интерфейса включает в себя тестирование двух основных сегментов: 1. Интерфейс веб-сервера и сервера приложений, 2. Интерфейс сервера приложений и базы данных"`. Я видел откуда это взялось, но даже там я не понял, что они имели в виду

5. `"Во время тестирования интерфейса выполняются различные типы тестирования, которые могут включать..."` там какая-то каша совсем.

**Comment by Vladislav610** [comment]
Добрый день, к сожалению, пока очереди из сеньоров, желающих помогать, нет. На выходных попробую еще раз самостоятельно перелопатить открытые источники и переписать обозначенное. Спасибо за обратную связь!

**Comment by who609102** [comment]
Вы сделали безусловно большую работу, за что вам огромное спасибо. Я только сегодня наткнулся на эту компиляцию и наугад решил посмотреть тему, в которой плаваю сам, чтобы разобраться, но в итоге получилась еще большая путаница. Возможно, если вы будете оставлять только ту информацию, которую понимаете сами на 100% в той формулировке, в которой приводите, то получится меньший объем, но информация будет более ценная. Буду рад дать обратную связь, если перепишете часть про интерфейсы.

**Comment by greenbeam** [comment]
(UI testing) - не относится к описанию в разделе ниже.
Можно классифицировать как тестирование интерфейсов вроде API, потоковых интерфейсов, интерфейсов адаптеров и проч.

**Comment by Vladislav610** [comment]
Убрал спорные моменты в 2.0
